appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OaZmt6ldexv6Tk3KgScIeqKAnIwJ/PC6KAr2wsrb4oXXBcg/NyeZUcdUrbjqVbVzRystCOi1oClFGHwmsgj/JgYgq4eWzR+ZxlZZH7i8PaTn+f8DAthc547UUf10RIi+maZXiGT8VjjhplZ6p4xLuK3cFz37P5kJ85AIWcDs7EfEYVbE7mpynr+2LX2DHkGv/JyYAsIoKhgvsMThhguvtKfnHmgGJhFEt1M9bfyRIsFlK8OChzPvUd1bmoNV+cUGXkjJfQUGV9cRjQHVRJ8tqOJCcYZze16jzakPimjvmV13A9xsY8vK4OoncAzeH6ew3WkbejaTH/od1ZFj1dgzxA55F5B0PUl/XtqWFBLEF1a7yvQ0U7ddLpGhz7TT2avStWT9i9ARdhn3CNdw+Q2DRaPUBJfhpRp+N685xBYOuNOhiT2USEtube559aPP8Q/Z/zPdV7cyqFXCvYymrldthEsYbu6cAXDOqyZueo3xiY/z9Je+Lw/EbPM6NTjBkylv+MfslHClOXdfNRNxUsn8xvOcvcl8Z62uOVi9lHbIzsfKSebHofwc8qSve98LJUg9Hh+GRnQVNlZe9O31n9EWmku+zI7WZppgx+cDISp/V9hJCjTzc365JiKXUBOI9EmFK1I5RbipBzAxTOX9U2vBhOh5pQeH/bVyy14zZHDlCd4=}
bot:
  automerge: true
